### PR TITLE
Oada-client.put stall bugfix

### PR DESCRIPTION
**Pull request by aaron97neu**
Discovered an issue while deploying our ISOBlues in Ault's farm. Very occasionally (several times a day) the `oada.put` call would not return, and this would cause the program to stop uploading data until I restarted the container.

Currently testing on the test stand, awaiting the ISOBlues on Ault's farm to come back online so I can test this fully

Not super happy with the `if( res === undefined )` solution I ended up implementing. @abalmos if you have a better suggestion, I would love to hear about it

Ended up deleting the outdated `gps.sql` file as well because it was causing problems

### CODE REVIEW

**Comment by abalmos** [comment]
Do we know if the failed response is in the client or server? I do know that we have had trouble with websockets in the past. Is the oada server running the newest release? @awlayton and /or @aultac might have some better context on that issue.

**Comment by aultac** [comment]
I think Aaron was going to upgrade it to OADAv2 but it was not currently running OADAv2.

Aaron

**Comment by aaron97neu** [comment]
The OADA server on OATS2 is now tracking most recent master. No failed response on the client side, the function call just never returns. I did not check the server logs or enable debugging output on oada-client (yet)

**Comment by aaron97neu** [comment]
Update - simply doing another put when it times out does not seem to solve the issue, subsequent puts also timeout. Trying a few other things, worst case will have to exit the container and let docker restart it
```
Found batch of 1000 GPS points
Head time: Wed Aug 12 2020 12:36:39 GMT+0000 (Coordinated Universal Time)
996 points to OADA /bookmarks/isoblue/device-index/165-feeder/location/day-index/2020-08-12/hour-index/12
4 points to OADA /bookmarks/isoblue/device-index/165-feeder/location/day-index/2020-08-11/hour-index/18
Error Uploading to OADA: %p Error: oada.put timed out
    at /code/src/oada_upload.ts:329:17
    at Generator.next (<anonymous>)
    at fulfilled (/code/src/oada_upload.ts:11:58)
    at runNextTicks (internal/process/task_queues.js:58:5)
    at listOnTimeout (internal/timers.js:520:9)
    at processTimers (internal/timers.js:494:7) oada.put timed out oada.put timed out   undefined
Error Uploading to OADA: %p Error: oada.put timed out
    at /code/src/oada_upload.ts:329:17
    at Generator.next (<anonymous>)
    at fulfilled (/code/src/oada_upload.ts:11:58) oada.put timed out oada.put timed out   undefined
Found batch of 1000 GPS points
Head time: Wed Aug 12 2020 12:36:44 GMT+0000 (Coordinated Universal Time)
1000 points to OADA /bookmarks/isoblue/device-index/165-feeder/location/day-index/2020-08-12/hour-index/12
Error Uploading to OADA: %p Error: oada.put timed out
    at /code/src/oada_upload.ts:329:17
    at Generator.next (<anonymous>)
    at fulfilled (/code/src/oada_upload.ts:11:58) oada.put timed out oada.put timed out   undefined
Found batch of 1000 GPS points
Head time: Wed Aug 12 2020 12:36:50 GMT+0000 (Coordinated Universal Time)
1000 points to OADA /bookmarks/isoblue/device-index/165-feeder/location/day-index/2020-08-12/hour-index/12

```

**Comment by abalmos** [comment]
Do those points succeed after the restart? Does this only happen when you have a large backlog of points to push? I have seen OADA timeout under too much write load before. Wondering if the docker restart just gives it enough time to get "caught up"

**Comment by aaron97neu** [comment]
After restarting the container, it always succeeds. I do not think there is a connection with the number of points to upload. It tends to fail when it is caught up (uploading 1 - 2 points at a time). After I restart it, it always works fine (and is uploading ~900 points per put as it catches up). The example I showed has the 900 points per put because the backlog was building up as it kept failing

Will keep an eye on the server load in the future. Should I be looking for something besides CPU usage to determine how bogged down the OADA server is?

**Comment by abalmos** [comment]
(In my limited experience) OADA seems to fail in two ways:

- overloaded CPU
- no load (connections to Kafka break)

If you don't have to touch the server to fix things, then it's not the
latter. Having a hard time predicting how the client library causes a
timeout.

Unless the timeout is some timer in the client itself waiting for the
server to respond? In that case, maybe the client has a bug where the put
is not made and then the timeout eventually returns? I don't know how that
part of client works

Andrew

**Comment by aaron97neu** [comment]
I think I have narrowed it down to `oada-client` having issues on resume from suspend. By turning on and off the CAN messages to dev05 on the test stand, I can reliably cause the oada-put call to freeze on resume.

An example log. Notice the ~7min gap in the log right before the timeout and subsequent restart. Left it long to keep the context
```
2020-08-13T01:21:59.929465495Z No unsent data found in database
2020-08-13T01:22:00.993698037Z Found batch of 1 GPS points
2020-08-13T01:22:00.994142295Z Head time: Thu Aug 13 2020 01:22:00 GMT+0000 (Coordinated Universal Time)
2020-08-13T01:22:00.996896160Z 1 points to OADA /bookmarks/isoblue/device-index/isoblue-dev-5/location/day-index/2020-08-13/hour-index/01
2020-08-13T01:22:01.567038126Z Done uploading to OADA
2020-08-13T01:22:01.567229427Z Updating database for 1 ids
2020-08-13T01:22:01.567680683Z 1 rows to update
2020-08-13T01:22:01.675468672Z Found batch of 1 GPS points
2020-08-13T01:22:01.675678303Z Head time: Thu Aug 13 2020 01:22:01 GMT+0000 (Coordinated Universal Time)
2020-08-13T01:22:01.687191010Z 1 points to OADA /bookmarks/isoblue/device-index/isoblue-dev-5/location/day-index/2020-08-13/hour-index/01
2020-08-13T01:22:01.875647270Z Done uploading to OADA
2020-08-13T01:22:01.875832905Z Updating database for 1 ids
2020-08-13T01:22:01.876307491Z 1 rows to update
2020-08-13T01:22:01.940121297Z No unsent data found in database
2020-08-13T01:27:17.361089879Z Found batch of 1 GPS points
2020-08-13T01:27:17.361917072Z Head time: Thu Aug 13 2020 01:22:02 GMT+0000 (Coordinated Universal Time)
2020-08-13T01:27:17.365803743Z 1 points to OADA /bookmarks/isoblue/device-index/isoblue-dev-5/location/day-index/2020-08-13/hour-index/01
2020-08-13T01:27:22.373721704Z oada.put timed out
2020-08-13T01:27:22.559469534Z error Command failed with exit code 255.
2020-08-13T01:27:22.561425023Z info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2020-08-13T01:27:28.528620792Z yarn run v1.22.4
2020-08-13T01:27:29.007334399Z $ ts-node src/oada_upload.ts
2020-08-13T01:27:49.903745906Z Options from enviroment lets:
2020-08-13T01:27:49.903936222Z     Batch size: 1000
2020-08-13T01:27:49.904102540Z     ID: isoblue-dev-5
2020-08-13T01:27:49.904183200Z     Domain: oats2.ecn.purdue.edu
2020-08-13T01:27:49.904261859Z     Token: pIhEHwLtQiyuEpT1xKLtPzTasTJl58kGFNqBGlpd
2020-08-13T01:27:49.904338185Z     DB User: avena
2020-08-13T01:27:49.904413179Z     DB Host: postgres
2020-08-13T01:27:49.904485505Z     DB Database: avena
2020-08-13T01:27:49.904557166Z     DB Password password
2020-08-13T01:27:49.904631826Z     DB Port 5432
2020-08-13T01:27:49.909631039Z Creating databse client
2020-08-13T01:27:49.916049791Z Connecting to database
2020-08-13T01:27:50.011202832Z Activating timescaledb extension
2020-08-13T01:27:50.052331104Z Ensuring GPS DB table exists
2020-08-13T01:27:50.090340325Z Ensuring own sent table exists
2020-08-13T01:27:50.095061231Z Ensuring sent table is a timescaledb hypertable
2020-08-13T01:27:50.102575550Z Ensuring triggers to sync gps ids to sent db are created
2020-08-13T01:27:50.103304150Z  Creating sent row procedure
2020-08-13T01:27:50.117247886Z  Creating trigger for creating rows
2020-08-13T01:27:50.133397422Z  Creating delete row procedure
2020-08-13T01:27:50.140155143Z  Creating trigger for deleting rows
2020-08-13T01:27:50.162169148Z Connecting to OADA: oats2.ecn.purdue.edu
2020-08-13T01:27:50.317338749Z (node:29) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
2020-08-13T01:27:50.317556729Z (Use `node --trace-warnings ...` to show where the warning was created)
2020-08-13T01:27:50.398241416Z Found batch of 34 GPS points
2020-08-13T01:27:50.401743098Z Head time: Thu Aug 13 2020 01:27:50 GMT+0000 (Coordinated Universal Time)
2020-08-13T01:27:50.508867388Z 34 points to OADA /bookmarks/isoblue/device-index/isoblue-dev-5/location/day-index/2020-08-13/hour-index/01
2020-08-13T01:27:51.405745423Z Done uploading to OADA
2020-08-13T01:27:51.405978402Z Updating database for 34 ids
2020-08-13T01:27:51.406508354Z 34 rows to update
2020-08-13T01:27:51.497620762Z Found batch of 1 GPS points
2020-08-13T01:27:51.498142381Z Head time: Thu Aug 13 2020 01:27:51 GMT+0000 (Coordinated Universal Time)
2020-08-13T01:27:51.500959126Z 1 points to OADA /bookmarks/isoblue/device-index/isoblue-dev-5/location/day-index/2020-08-13/hour-index/01
2020-08-13T01:27:51.694768558Z Done uploading to OADA
2020-08-13T01:27:51.695320508Z Updating database for 1 ids
2020-08-13T01:27:51.695454829Z 1 rows to update
2020-08-13T01:27:51.761464846Z No unsent data found in database
2020-08-13T01:27:52.820048557Z Found batch of 1 GPS points
2020-08-13T01:27:52.820400525Z Head time: Thu Aug 13 2020 01:27:52 GMT+0000 (Coordinated Universal Time)
2020-08-13T01:27:52.822205361Z 1 points to OADA /bookmarks/isoblue/device-index/isoblue-dev-5/location/day-index/2020-08-13/hour-index/01
2020-08-13T01:27:53.343171472Z Done uploading to OADA
2020-08-13T01:27:53.343631763Z Updating database for 1 ids
2020-08-13T01:27:53.343745086Z 1 rows to update
```

Will continue to investigate on the machines in the field over the next couple days

**Comment by aaron97neu** [comment]
Since this is an issue with the library and the bugfix provides us with the workaround, I am going to merge this in unless there is ay discussion about how the workaround was implemented

**Pull request merged**
